# what is the goal of your workflow
# Goal: whenever some one changes the python code, 
# the linter will check if the syntax, format, indentation(linting) is correct or not.

name: Auto Linter
on: 
 push: 
  paths: "*.py"

jobs:
  code:
   runs-on: ubuntu-latest
   # this step will automatically clone the code of the current branch into the runner
   steps:
     - name: checkout/clone the code
       uses: actions/checkout@v7

     - name: Setup python
       uses: actions/setup-python@v5
       with:
        python-version: '3.14'

     - name: install linter
       run: pip install ruff

     - name: checkout the files for linting
       run: ruff check . --fix
